import React, { useEffect, useMemo, useState } from 'react';
import { CampusProvider, useCampus, type CampusRuntime } from './CampusContext';
import { TopBar } from './TopBar';
import { useCampusBootstrap } from '@/hooks/useCampusBootstrap';
import { useEdit } from '@/store/editStore';
import { EditPanel } from '@/features/editor/EditPanel';
import { mergeEditSession } from '@/data/mergeEdits';
import { mergeRoadSessionChecked, connectivityShare } from '@/data/roadEdits';
import { buildOutdoorGraph } from '@/geo/routing';
import { useDeepLink, useDeepLinkFocus } from '@/hooks/useDeepLink';
import { useGlobalShortcuts } from '@/hooks/useGlobalShortcuts';
import { ShortcutsOverlay } from './ShortcutsOverlay';
import { useUi } from '@/store/uiStore';
import type { PanelId } from '@/store/uiStore';
import { useOutdoor } from '@/store/outdoorStore';
import { featureFlags } from '@/config/featureFlags';
// Heavy engines are code-split: three.js/r3f and maplibre-gl only download when the
// view that needs them is opened, which keeps the entry bundle inside the budget.
const Campus3D = React.lazy(() => import('@/scene/Campus3D').then((m) => ({ default: m.Campus3D })));
const Map2D = React.lazy(() => import('@/features/map/Map2D').then((m) => ({ default: m.Map2D })));
import { IndoorShell } from '@/features/indoor/IndoorShell';
import { ExplorePanel } from '@/features/explore/ExplorePanel';
import { LayersPanel } from '@/features/layers/LayersPanel';
import { RoutePanel } from '@/features/route/RoutePanel';
import { AboutPanel } from '@/features/about/AboutPanel';
import { PrintSheet } from '@/features/print/PrintSheet';
import { Compass } from '@/features/common/Compass';
import { Onboarding } from '@/features/common/Onboarding';
import { Toast } from '@/features/common/Toast';
import { EmptyState, ProgressStages } from '@/ui/primitives';
import { IconBuilding, IconInfo, IconLayers, IconRoute, IconSearch, IconClose, IconEdit } from '@/ui/Icons';

export function App() {
  const bootstrap = useCampusBootstrap();
  const isPrint = typeof window !== 'undefined' && new URLSearchParams(window.location.search).get('print') === '1';

  if (bootstrap.status === 'loading') {
    return (
      <div style={{ height: '100%', display: 'grid', placeItems: 'center', background: 'var(--bg)' }}>
        <ProgressStages stage={bootstrap.stage} />
      </div>
    );
  }

  if (bootstrap.status === 'error') {
    return (
      <div style={{ height: '100%', display: 'grid', placeItems: 'center', background: 'var(--bg)' }}>
        <EmptyState
          art="grid"
          title="Could not load the campus data"
          body={
            <>
              <span className="mono">{bootstrap.error}</span>
              <br />
              The terrain, footprints and imagery are served from <code>public/data/…</code>. If those files are
              missing the map cannot be built — it will not silently fall back to something invented.
            </>
          }
          action={<button className="btn btn-primary" onClick={() => window.location.reload()}>Retry</button>}
        />
      </div>
    );
  }

  return <LoadedApp bootstrap={bootstrap} isPrint={isPrint} />;
}

function LoadedApp({ bootstrap, isPrint }: { bootstrap: Extract<ReturnType<typeof useCampusBootstrap>, { status: 'ready' }>; isPrint: boolean }) {
  // the manual-edit session (if any) is merged on top of the loaded data so corrections
  // preview immediately; exported files then reproduce exactly the same result on reload
  const saved = useEdit((s) => s.saved);
  const addedBuildings = useEdit((s) => s.addedBuildings);
  const addedLabels = useEdit((s) => s.addedLabels);
  const roadEdits = useEdit((s) => s.roadEdits);
  const hiddenRoads = useEdit((s) => s.hiddenRoads);
  const addedRoads = useEdit((s) => s.addedRoads);
  const draft = useEdit((s) => s.draft);
  const draftTarget = useEdit((s) => s.targetId);
  const datum = useEdit((s) => s.datum);

  // Live draft preview: fold the unsaved draft on top of the target building's saved
  // override so slider drags update the 3D + 2D scene immediately. Save simply persists
  // exactly what was already on screen — no "edit but nothing changes" confusion.
  const liveSaved = useMemo(
    () =>
      draftTarget && Object.keys(draft).length > 0
        ? { ...saved, [draftTarget]: { ...(saved[draftTarget] ?? {}), ...draft } }
        : saved,
    [saved, draft, draftTarget],
  );

  const runtime: CampusRuntime = useMemo(() => {
    const merged = mergeEditSession(bootstrap.data, bootstrap.searchIndex, { saved: liveSaved, addedBuildings, addedLabels });

    // ── v3.2 campus datum correction ── generated content was authored against an
    // older/sloppier imagery epoch; the user slides EVERYTHING generated by metres
    // until it sits on the z18 HD ortho. Manual content (hand-drawn roads, override
    // rings, manual buildings, hand-set doors) is ALREADY imagery-true and untouched.
    const { dxM, dyM } = datum;
    if (dxM !== 0 || dyM !== 0) {
      const lat0 = (bootstrap.data.roads[0]?.line[0]?.[1] ?? 31.779);
      const dLng = dxM / (111320 * Math.cos((lat0 * Math.PI) / 180));
      const dLat = dyM / 110540;
      const manualRoadIds = new Set(addedRoads.map((r) => r.id));
      merged.data.roads = merged.data.roads.map((r) => {
        // a road with a saved hand-fix is imagery-true — never slide it
        if (roadEdits[r.id] || manualRoadIds.has(r.id)) return r;
        return { ...r, line: r.line.map(([lng, lat]) => [lng + dLng, lat + dLat] as [number, number]) };
      });
      merged.data.buildings = merged.data.buildings.map((b) => {
        if (b.manual) return b;
        const ov = liveSaved[b.id];
        if (ov?.ring) return b; // user reshaped it on the imagery — already true
        const out = { ...b, ring: b.ring.map(([lng, lat]) => [lng + dLng, lat + dLat] as [number, number]) as [number, number][] };
        if (ov?.entrance_lat != null) { /* hand-set door: untouched */ }
        else if (b.entrance_lat != null && b.entrance_lng != null) { out.entrance_lat = b.entrance_lat + dLat; out.entrance_lng = b.entrance_lng + dLng; }
        return out;
      });
      // terrain seams stay put: terrain is absolute DEM — the visible cut platforms
      // track the terrain grid, so a few-metre slide reads fine (diagonal smoothing).
    }

    // Manual route layer (§1, v3 blueprint): per-road ADMISSION replaces the old
    // whole-session rollback — the base network measures 0.8846 connectivity, so a
    // ≥0.999 gate had silently rejected EVERY hand-drawn road since v1.8. Now each
    // drawn road joins by projection-and-split onto existing roads, one-end spurs
    // count as valid (dead-end drives are real campus topology), and only roads
    // connecting to NOTHING are listed as issues (amber chips, never dropped).
    // Safety invariant preserved: merged network still rolls back if it would
    // DECREASE connectivity versus the base share.
    // v3.1 roads the user DELETED are removed before everything else: the network —
    // and the connectivity baseline — is measured against what the user actually kept.
    const poolsRoads = hiddenRoads.length > 0 ? merged.data.roads.filter((r) => !hiddenRoads.includes(r.id)) : merged.data.roads;
    const roadsTouched = Object.keys(roadEdits).length > 0 || addedRoads.length > 0 || hiddenRoads.length > 0;
    let roads = poolsRoads;
    let graph = bootstrap.graph;
    if (roadsTouched) {
      const hideKey = hiddenRoads.join('|');
      const memo = (globalThis as { __baseShare?: number; __baseKey?: string });
      const baseShare = memo.__baseKey === hideKey && memo.__baseShare !== undefined
        ? memo.__baseShare
        : connectivityShare(buildOutdoorGraph(poolsRoads, bootstrap.terrain, { buildings: merged.data.buildings }));
      memo.__baseShare = baseShare;
      memo.__baseKey = hideKey;
      const checked = mergeRoadSessionChecked(poolsRoads, roadEdits, addedRoads);
      useUi.getState().setRoadIssues(checked.issues);
      useUi.getState().setRoadJoins(checked.joined);
      try {
        const g = buildOutdoorGraph(checked.roads, bootstrap.terrain, { buildings: merged.data.buildings });
        const mergedShare = connectivityShare(g);
        if (mergedShare >= baseShare - 0.001) {
          roads = checked.roads;
          graph = g;
          if (checked.issues.length > 0) {
            useUi.getState().notify(
              `${checked.issues.length} hand-drawn road(s) saved but NOT routable: ${checked.issues
                .slice(0, 2)
                .map((i) => `${i.name ?? i.id} (gap ${Number.isFinite(i.gapM) ? i.gapM.toFixed(0) : '∞'} m at its ${i.end})`)
                .join('; ')}${checked.issues.length > 2 ? '…' : ''}. Extend them to an existing road — Edit tab → Routes has a Fix now assist.`,
              'warn',
            );
          }
        } else {
          useUi.getState().notify('Road edits were rolled back: they broke network connectivity. Fix a crossing/junction and try again.', 'error');
          // eslint-disable-next-line no-console
          console.error(`[route-editor] merged share ${mergedShare.toFixed(3)} < base ${baseShare.toFixed(3)} — session roads rolled back`);
        }
      } catch (err) {
        // eslint-disable-next-line no-console
        console.error('[route-editor] graph rebuild failed, keeping generated network', err);
      }
    } else {
      useUi.getState().setRoadIssues([]);
      useUi.getState().setRoadJoins({});
    }

    return {
      data: { ...merged.data, roads },
      terrain: bootstrap.terrain,
      graph,
      searchIndex: merged.searchIndex,
      byId: merged.byId,
      builtMs: bootstrap.builtMs,
    };
  }, [bootstrap, liveSaved, addedBuildings, addedLabels, roadEdits, addedRoads, hiddenRoads, datum]);

  return (
    <CampusProvider value={runtime}>
      {isPrint ? <PrintSheet /> : <Shell />}
    </CampusProvider>
  );
}


/* ─────────────────────────────────────────────────────────────────────────────
 * Rail and MobileTabs are defined at MODULE SCOPE on purpose.
 *
 * They used to be declared inside <Shell>, which meant every Shell render handed
 * React a brand-new component type and forced a full unmount/remount of the rail
 * subtree. Combined with RoutePanel writing `status: 'computing'` into a store
 * that Shell also subscribes to, that produced an endless remount loop: the route
 * panel remounted ~30x/second, its 60 ms compute timer was cancelled every time
 * before it could fire, and turn-by-turn navigation never produced a result.
 * Keeping the identity stable is what makes the panel's state and effects survive.
 * ──────────────────────────────────────────────────────────────────────────── */

import { IconIndoor } from '@/ui/Icons';

function useRailTabs() {
  const editEnabled = useEdit((s) => s.enabled);
  const featureIndoor = featureFlags.indoor;
  return useMemo(
    () => [
      { id: 'explore' as const, label: 'Explore', icon: <IconSearch /> },
      { id: 'layers' as const, label: 'Layers', icon: <IconLayers /> },
      { id: 'route' as const, label: 'Route', icon: <IconRoute /> },
      ...(featureIndoor ? [{ id: 'indoor' as const, label: 'Indoor', icon: <IconIndoor /> }] : []),
      ...(editEnabled ? [{ id: 'edit' as const, label: 'Edit', icon: <IconEdit /> }] : []),
      { id: 'about' as const, label: 'About', icon: <IconInfo /> },
    ],
    [editEnabled, featureIndoor],
  );
}

function Rail({ open, onToggle }: { open: boolean; onToggle: () => void }) {
  const panel = useUi((s) => s.panel);
  const setPanel = useUi((s) => s.setPanel);
  const mode = useUi((s) => s.mode);
  const setMode = useUi((s) => s.setMode);
  const TABS = useRailTabs();
    return (
      <div className="rail" style={{ height: '100%', display: 'flex', flexDirection: 'column', minHeight: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 4, padding: 8, borderBottom: '1px solid var(--hairline)' }}>
          {TABS.map((t) => (
            <button
              key={t.id}
              className="btn btn-icon"
              aria-pressed={panel === t.id}
              title={t.label}
              onClick={() => {
                if (t.id === 'indoor') {
                  setMode('indoor');
                  setPanel(null);
                } else {
                  setMode('outdoor');
                  setPanel(panel === t.id ? null : t.id);
                }
              }}
              style={{
                background: (panel === t.id || (t.id === 'indoor' && mode === 'indoor')) ? 'var(--accent)' : 'transparent',
                color: (panel === t.id || (t.id === 'indoor' && mode === 'indoor')) ? 'var(--accent-ink)' : 'var(--text-2)',
                border: 0,
              }}
            >
              {t.icon}
            </button>
          ))}
          <button className="btn btn-icon" style={{ marginLeft: 'auto', border: 0, background: 'transparent' }} onClick={onToggle} aria-label={open ? 'Collapse panel' : 'Expand panel'}>
            {open ? <IconClose /> : <IconBuilding />}
          </button>
        </div>
        {open && (
          <div style={{ overflow: 'auto', flex: 1, minHeight: 0 }} className="fade-in">
            {panel === 'explore' && <ExplorePanel />}
            {panel === 'layers' && <LayersPanel />}
            {panel === 'route' && <RoutePanel />}
            {panel === 'indoor' && <IndoorShell />}
            {panel === 'edit' && <EditPanel />}
            {panel === 'about' && <AboutPanel />}
            {panel === null && (
              <EmptyState
                art="grid"
                title="Everything is one tap away"
                body="Explore what is on campus, control the layers, plan a walk, or read how accurate this model is."
              />
            )}
          </div>
        )}
      </div>
    );
  }


function MobileTabs({ onPick }: { onPick: (id: PanelId) => void }) {
  const panel = useUi((s) => s.panel);
  const TABS = useRailTabs();
    return (
      <div style={{ display: 'flex', gap: 6, padding: '8px 8px 0' }}>
        {TABS.map((t) => (
          <button
            key={t.id}
            className="btn"
            onClick={() => {
              onPick(t.id);
            }}
            style={{
              flex: 1, minHeight: 36, background: panel === t.id ? 'var(--accent)' : 'var(--surface-2)',
              color: panel === t.id ? 'var(--accent-ink)' : 'var(--text-2)', borderColor: 'transparent', fontSize: 11.5,
            }}
          >
            {t.icon}
            <span>{t.label}</span>
          </button>
        ))}
      </div>
    );
  }

function Shell() {
  const mode = useUi((s) => s.mode);
  const view = useUi((s) => s.view);
  const setPanel = useUi((s) => s.setPanel);
  const railOpen = useUi((s) => s.railOpen);
  const toggleRail = useUi((s) => s.toggleRail);
  const theme = useUi((s) => s.theme);
  const onboarded = useUi((s) => s.onboarded);
  const routeReady = useOutdoor((s) => s.route.status === 'ready');
  const { data: campus, terrain } = useCampus();
  const [isNarrow, setIsNarrow] = useState(typeof window !== 'undefined' ? window.innerWidth < 900 : false);
  const [sheet, setSheet] = useState<'peek' | 'half' | 'full'>('peek');

  useDeepLink();
  useGlobalShortcuts();
  useDeepLinkFocus();

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
  }, [theme]);

  useEffect(() => {
    const onResize = () => setIsNarrow(window.innerWidth < 900);
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, []);

  useEffect(() => {
    if (routeReady) setSheet('half');
  }, [routeReady]);


  const body = (
    <div style={{ position: 'absolute', inset: 0, display: 'flex', overflow: 'hidden' }}>
      <div style={{ position: 'relative', flex: 1, minWidth: 0 }}>
        {mode === 'indoor' ? (
          <div style={{ position: 'absolute', inset: 0, background: 'var(--bg)' }}>
            <IndoorShell />
          </div>
        ) : (
          <React.Suspense fallback={<ViewportLoading label={view === '3d' ? 'Starting the 3D engine…' : 'Loading the map engine…'} />}>
            {view === '3d' ? <Campus3D data={campus} terrain={terrain} /> : <Map2D data={campus} />}
          </React.Suspense>
        )}
        {mode === 'outdoor' && view === '3d' && <Compass />}
      </div>

      {!isNarrow && (
        <aside
          style={{
            width: railOpen ? 'var(--rail-w)' : 56, flex: '0 0 auto', transition: 'width var(--dur) var(--ease)',
            display: 'flex', flexDirection: 'column', minHeight: 0,
          }}
        >
          <Rail open={railOpen} onToggle={toggleRail} />
        </aside>
      )}
    </div>
  );

  return (
    <div style={{ position: 'fixed', inset: 0, overflow: 'hidden' }}>
      <TopBar />
      <div style={{ position: 'absolute', inset: 0, paddingTop: 0 }}>{body}</div>

      {isNarrow && (
        <MobileSheet sheet={sheet} setSheet={setSheet}>
          <MobileTabs onPick={(id) => { setPanel(id); setSheet('half'); }} />
        </MobileSheet>
      )}

      <Toast />
      {!onboarded && <Onboarding />}
      <ShortcutsOverlay />
    </div>
  );

}

function ViewportLoading({ label }: { label: string }) {
  return (
    <div style={{ position: 'absolute', inset: 0, display: 'grid', placeItems: 'center', background: 'var(--bg)' }}>
      <ProgressStages stage={label} />
    </div>
  );
}

function MobileSheet({
  sheet,
  setSheet,
  children,
}: {
  sheet: 'peek' | 'half' | 'full';
  setSheet: (s: 'peek' | 'half' | 'full') => void;
  children: React.ReactNode;
}) {
  const heights = { peek: 62, half: '46vh', full: '82vh' } as const;
  return (
    <div
      className="glass sheet"
      style={{
        position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 30,
        height: heights[sheet], borderTopLeftRadius: 'var(--r-lg)', borderTopRightRadius: 'var(--r-lg)',
        display: 'flex', flexDirection: 'column', overflow: 'hidden',
      }}
    >
      <button
        onClick={() => setSheet(sheet === 'peek' ? 'full' : sheet === 'half' ? 'peek' : 'half')}
        aria-label="Resize panel"
        style={{ height: 24, background: 'transparent', border: 0, cursor: 'grab', padding: 0 }}
      >
        <span style={{ display: 'block', width: 42, height: 4, borderRadius: 999, background: 'var(--hairline-strong)', margin: '10px auto 0' }} />
      </button>
      {children}
      <div style={{ overflow: 'auto', flex: 1, minHeight: 0 }}>
        <SheetContent />
      </div>
    </div>
  );
}

function SheetContent() {
  const panel = useUi((s) => s.panel);
  return (
    <>
      {panel === 'explore' && <ExplorePanel />}
      {panel === 'layers' && <LayersPanel />}
      {panel === 'route' && <RoutePanel />}
      {panel === 'indoor' && <IndoorShell />}
      {panel === 'edit' && <EditPanel />}
      {panel === 'about' && <AboutPanel />}
    </>
  );
}
