import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'] });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await context.addInitScript(() => { localStorage.clear(); });
const page = await context.newPage();
const errors = [];
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
const wait = (ms) => page.waitForTimeout(ms);
const text = async () => (await page.locator('body').innerText()).replace(/\s+/g,' ');
const check = async (name, condition) => { if (!condition) throw new Error(`FAIL: ${name}`); console.log(`PASS: ${name}`); };
await page.goto('http://127.0.0.1:5173/?edit=1', { waitUntil: 'domcontentloaded' });
await wait(5000);
await page.getByRole('button', { name: /Skip/i }).first().click().catch(()=>{});
await wait(500);
await page.locator('button[title="Edit"]').first().waitFor({ timeout: 60000 });
await page.locator('button[title="Edit"]').first().click();
await wait(600);
const a1 = page.locator('.rail button').filter({ hasText: /^A1/ }).first();
await a1.click();
await wait(500);
const nameLabel = page.locator('input[aria-label="Label text"]').first();
await nameLabel.fill('A1 manual label');
await page.getByRole('button', { name: 'Save change', exact: true }).click();
let saved = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('building label correction saved', saved.saved?.['osm-474553719']?.labelText === 'A1 manual label');
await page.getByRole('button', { name: 'Remove building', exact: true }).click();
saved = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('previous building can be removed from the map', saved.saved?.['osm-474553719']?.hidden === true);
await page.getByRole('button', { name: 'Restore building', exact: true }).click();
saved = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('removed building can be restored', saved.saved?.['osm-474553719']?.hidden === false);
await page.locator('input[aria-label="Label text to place"]').fill('North gate manual');
await page.locator('input[aria-label="Label coordinates"]').fill('31.77555, 76.98654');
await page.getByRole('button', { name: 'Add label', exact: true }).click();
let state = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('manual label can be added', state.addedLabels?.length === 1 && state.addedLabels[0].text === 'North gate manual');
const editLabel = page.locator('input[aria-label^="Edit label"]').first();
await editLabel.fill('North gate corrected');
state = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('manual label can be edited', state.addedLabels?.[0]?.text === 'North gate corrected');
await page.getByTitle(/plan|satellite/i).first().click();
await page.waitForFunction(() => window.__map2d?.loaded?.() === true, { timeout: 30000 }).catch(() => {});
await wait(5000);
await check('manual label is visible in the 2D view', await page.locator('.manual-map-label').count() === 1);
await page.getByRole('button', { name: 'Remove', exact: true }).last().click();
state = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('manual label can be removed', state.addedLabels?.length === 0);
await page.getByRole('button', { name: 'Trace a footprint', exact: true }).click();
await wait(1800);
const canvas = page.locator('.maplibregl-canvas').first();
await check('trace switched to the 2D map', await canvas.count() === 1);
for (const p of [{x:260,y:260},{x:360,y:260},{x:360,y:360},{x:260,y:360}]) await canvas.click({ position: p });
await wait(300);
await page.getByRole('button', { name: 'Close shape', exact: true }).click();
await page.locator('input[aria-label="New building name"]').fill('Manual Test Building');
await page.getByRole('button', { name: 'Save footprint', exact: true }).click();
state = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('manual building can be created', state.addedBuildings?.length === 1 && state.addedBuildings[0].properties.name === 'Manual Test Building');
const removeAdded = page.locator('li').filter({ hasText: 'Manual Test Building' }).getByRole('button', { name: 'Remove', exact: true });
await removeAdded.click();
state = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-edits-v1') || '{}'));
await check('manual building can be removed', state.addedBuildings?.length === 0);
await page.getByTitle(/Indoor/i).click();
await wait(1500);
await page.locator('li button').filter({ hasText: /^A1/ }).first().click();
await wait(600);
const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="800" height="500" fill="#ddd"/><path d="M20 20H780V480H20Z M400 20V480" fill="none" stroke="#111" stroke-width="8"/></svg>';
await page.locator('input[aria-label="Upload digital floor footprint"]').setInputFiles({ name: 'a1-ground.svg', mimeType: 'image/svg+xml', buffer: Buffer.from(svg) });
await wait(800);
await check('floor plan upload creates a digital floor map', (await text()).toLowerCase().includes('digital floor map'));
const floorMap = page.locator('.floor-map-editor');
await check('uploaded floor map viewport is present', await floorMap.count() === 1);
await floorMap.click({ position: { x: 180, y: 150 } });
await page.locator('input[aria-label="New floor label"]').fill('Room 101');
await page.getByRole('button', { name: 'Save label', exact: true }).click();
await floorMap.click({ position: { x: 500, y: 300 } });
await page.locator('input[aria-label="New floor label"]').fill('Main door');
await page.locator('select[aria-label="Floor label kind"]').selectOption('door');
await page.getByRole('button', { name: 'Save label', exact: true }).click();
await wait(400);
await check('floor labels can be placed manually', await page.locator('.floor-label').count() === 2);
const connFrom = page.locator('select[aria-label="Floor connection start"]');
const connTo = page.locator('select[aria-label="Floor connection destination"]');
const values = await connFrom.locator('option').evaluateAll(opts => opts.map(o => o.value).filter(Boolean));
await connFrom.selectOption(values[0]); await connTo.selectOption(values[1]);
await page.getByRole('button', { name: 'Add connection', exact: true }).click();
await page.locator('select[aria-label="Indoor route start"]').selectOption(values[0]);
await page.locator('select[aria-label="Indoor route destination"]').selectOption(values[1]);
await page.getByRole('button', { name: 'Find floor route', exact: true }).click();
await wait(300);
await check('manual floor connection returns a route', (await text()).includes('Route ready through 2 manual points'));
await check('floor route is drawn in red', await floorMap.locator('polyline').count() === 1 && await floorMap.locator('polyline').getAttribute('stroke') === '#ff304f');
const localFloor = await page.evaluate(() => JSON.parse(localStorage.getItem('iitm-nav-indoor-v1') || '{}'));
await check('floor map and labels persist locally', localFloor.buildings?.[0]?.floors?.[0]?.labels?.length === 2);
console.log(`console errors: ${errors.length}`);
if (errors.length) console.log(errors.join('\n'));
await browser.close();
